"""empty message

Revision ID: 0025e9a5d00c
Revises: 030f3f4ad44f
Create Date: 2024-02-26 20:38:08.797833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0025e9a5d00c'
down_revision = '030f3f4ad44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.alter_column('phrase',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('phrase',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
