"""empty message

Revision ID: 030f3f4ad44f
Revises: 0e0f1452e097
Create Date: 2024-02-26 20:35:37.299541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030f3f4ad44f'
down_revision = '0e0f1452e097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    # ### end Alembic commands ###
