"""empty message

Revision ID: 0e0f1452e097
Revises: e0af38852743
Create Date: 2024-02-21 03:48:20.834095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0f1452e097'
down_revision = 'e0af38852743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psycho_consultation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psycho_consultation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='psycho_consultation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='psycho_consultation_pkey')
    )
    # ### end Alembic commands ###
