"""empty message

Revision ID: 13f0fc53489e
Revises: 2d96bfe59876
Create Date: 2024-08-04 05:02:55.944254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f0fc53489e'
down_revision = '2d96bfe59876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facturacion', sa.String(length=400), nullable=True),
    sa.Column('product', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(length=400), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=400), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(length=400), nullable=True),
    sa.Column('psychologist_id_marketplace', sa.Integer(), nullable=True),
    sa.Column('client_id_marketplace', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id_marketplace'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id_marketplace'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace')
    op.drop_table('factura')
    op.drop_table('client_list')
    # ### end Alembic commands ###
