"""empty message

Revision ID: 205876fd5e11
Revises: 83df79f9f0eb
Create Date: 2024-05-30 10:05:30.744613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205876fd5e11'
down_revision = '83df79f9f0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint('session_psychologist_session_id_fkey', type_='foreignkey')
        batch_op.drop_column('psychologist_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psychologist_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('session_psychologist_session_id_fkey', 'user', ['psychologist_session_id'], ['id'])

    # ### end Alembic commands ###
