"""empty message

Revision ID: 3c86a3d6db53
Revises: f1e6b87c4f07
Create Date: 2024-08-09 04:53:59.677038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c86a3d6db53'
down_revision = 'f1e6b87c4f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Numeric(precision=2), nullable=True))
        batch_op.add_column(sa.Column('month', sa.Numeric(precision=2), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Numeric(precision=4), nullable=True))
        batch_op.drop_constraint('user_dob_key', type_='unique')
        batch_op.create_unique_constraint(None, ['day'])
        batch_op.create_unique_constraint(None, ['month'])
        batch_op.create_unique_constraint(None, ['year'])
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_dob_key', ['dob'])
        batch_op.drop_column('year')
        batch_op.drop_column('month')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
