"""empty message

Revision ID: 4f1f2454490a
Revises: 7010257306a7
Create Date: 2024-06-12 15:20:14.774852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1f2454490a'
down_revision = '7010257306a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psychologist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['psychologist_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_list', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client_list', ['client_list'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_list')

    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('psychologist_id')

    # ### end Alembic commands ###
