"""empty message

Revision ID: 7010257306a7
Revises: 84eb106701fd
Create Date: 2024-06-12 15:14:33.753253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7010257306a7'
down_revision = '84eb106701fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psychologist_id_marketplace', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id_marketplace', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['client_id_marketplace'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['psychologist_id_marketplace'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id_marketplace')
        batch_op.drop_column('psychologist_id_marketplace')

    # ### end Alembic commands ###
