"""empty message

Revision ID: 83df79f9f0eb
Revises: bbfb8fe6413e
Create Date: 2024-05-30 09:19:24.788298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83df79f9f0eb'
down_revision = 'bbfb8fe6413e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_list')
    # ### end Alembic commands ###
