"""empty message

Revision ID: c318bb44273e
Revises: 95c6559a7405
Create Date: 2023-12-05 18:04:12.076267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c318bb44273e'
down_revision = '95c6559a7405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_description', sa.String(length=300), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_list_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_list', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mi_psicologo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Psicologo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Psicologo_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psycho_consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('psychologist_id')
    )
    op.create_table('user_profile_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('dni', sa.String(length=30), nullable=True),
    sa.Column('cedula', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('monto_consulta', sa.String(length=25), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('fpv_number', sa.String(length=25), nullable=True),
    sa.Column('specialty_area', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('twitter', sa.String(length=25), nullable=True),
    sa.Column('facebook', sa.String(length=25), nullable=True),
    sa.Column('instagram', sa.String(length=25), nullable=True),
    sa.Column('education', sa.String(length=140), nullable=True),
    sa.Column('motivo_consulta', sa.String(length=600), nullable=True),
    sa.Column('psych_strategies', sa.String(length=1000), nullable=True),
    sa.Column('PsychExperiences', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('fpv_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('psych_academic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('institute', sa.String(length=100), nullable=True),
    sa.Column('graduation_date', sa.String(length=30), nullable=True),
    sa.Column('certificate_url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psych_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psych_therapeutic_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile_info.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', 'description', name='unique_psych_image_url')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('room_number', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_psicologo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=80), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['salt'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('salt')
        batch_op.drop_column('is_online')
        batch_op.drop_column('is_psicologo')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('session')
    op.drop_table('psych_therapeutic_strategies')
    op.drop_table('psych_experiences')
    op.drop_table('psych_academic_info')
    op.drop_table('user_profile_info')
    op.drop_table('user_address')
    op.drop_table('schedule')
    op.drop_table('psycho_consultation')
    op.drop_table('mi_psicologo')
    op.drop_table('todo_list_container')
    op.drop_table('todo_list')
    # ### end Alembic commands ###
