"""empty message

Revision ID: d6597fd6bab1
Revises: 205876fd5e11
Create Date: 2024-05-30 10:08:56.780174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6597fd6bab1'
down_revision = '205876fd5e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psychologist_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['psychologist_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('psychologist_session_id')

    # ### end Alembic commands ###
