"""empty message

Revision ID: e87846aca77a
Revises: f039f6206e3f
Create Date: 2024-07-08 19:37:23.172087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87846aca77a'
down_revision = 'f039f6206e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facturacion', sa.String(length=400), nullable=True),
    sa.Column('product', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(length=400), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=400), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.String(length=400), nullable=True),
    sa.Column('psychologist_id_marketplace', sa.Integer(), nullable=True),
    sa.Column('client_id_marketplace', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id_marketplace'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id_marketplace'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Marketplace', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('factura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_list', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client_list', ['client_list'], ['id'])
        batch_op.create_foreign_key(None, 'factura', ['factura'], ['id'])
        batch_op.create_foreign_key(None, 'marketplace', ['Marketplace'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_list')
        batch_op.drop_column('factura')
        batch_op.drop_column('Marketplace')

    op.drop_table('marketplace')
    op.drop_table('factura')
    op.drop_table('client_list')
    # ### end Alembic commands ###
